StylesPath = styles
MinAlertLevel = suggestion

# Since .vale.ini is in docs/, and your vocab is in docs/styles/config/vocabularies/Base
Vocab = Base

[*.md]
BasedOnStyles = Vale, Microsoft, write-good

# Rules...
write-good.E-Prime = NO
write-good.TooWordy = NO
Microsoft.We = NO